class TestException(Exception):
  pass

class FatalTestException(Exception):
  pass